name: Daily workflow

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  generic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          cache: 'pnpm'

      - name: install dependencies
        run: pnpm i

      - name: build package
        run: pnpm build

      - name: publish package
        run: pnpm cron:daily

      - name: publish changes
        uses: stefanzweifel/git-auto-commit-action@v4